> **Note:** In most sessions you will be solving exercises posed in a Jupyter notebook that looks like this one. Because you are cloning a Github repository that only we can push to, you should **NEVER EDIT** any of the files you pull from Github. Instead, what you should do, is either make a new notebook and write your solutions in there, or **make a copy of this notebook and save it somewhere else** on your computer, not inside the `sds` folder that you cloned, so you can write your answers in there. If you edit the notebook you pulled from Github, those edits (possible your solutions to the exercises) may be overwritten and lost the next time you pull from Github. This is important, so don't hesitate to ask if it is unclear.

# Exercise set 1: Introduction to Python

*Morning, August 12, 2019*

In this session you will be working with core Python. We will go over some of the basic operations and functions in Python. You will learn to set up a `for` loop and write your own function.

### Exercise Section 1.0.: Check modules are working

Run the cell below to check you have all the relevant packages installed. You should get a scatter plot of `total_bill` and `tip` in the dataset `tips`.

In [1]:
# This part import the relevant packages 
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import requests
import seaborn as sns

# We load the dataset 'tips' from the seaborn package, and call the dataset tips
tips = sns.load_dataset('tips')
# We use seaborn to make a jointplot, with total_bill on the x-axis and tip on the y-axis, form the dataset tips.
sns.jointplot(x='total_bill', y='tip', data=tips)

# The plot is displayed
plt.show()

<Figure size 600x600 with 3 Axes>

## Exercises

### Exercise Section 1.1: Basic operations and functions
We start with some simple procedures for core Python.

> **Ex. 1.1.1**: Division in Python has two ways of usage. What is the output of `5/2`?  What is the output of `5//2`? What is the fundamental data type for each of the two operations? Explain your results.

> Note: Python 2 and 3 are different on what `/` does to integers! 

In [2]:
# [Answer to Ex. 1.1.1]

first = 5/2
second = 5//2

print(first)
print(second)
print('The first variable returns 2,5 and has the type float, the second returns 2 as it rounds down and has the type integer')

2.5
2
The first variable returns 2,5 and has the type float, the second returns 2 as it rounds down and has the type integer


> **Ex. 1.1.2
**: What happens if we use the modulus operator instead, i.e. `5%2`? What is the output of `5**2`? Explain your answers.

In [3]:
# [Answer to Ex. 1.1.2]
print(5%2)
print('The modulos operator devides left side of the operator with the right side, and returns that which remains')

1
The modulos operator devides left side of the operator with the right side, and returns that which remains


> **Ex. 1.1.3**: use expressions `<`, `>`, `==`, `!=` to compare 4 to 6 (e.g. run `4<6`)- what are the input data types? What are the output data types?

In [4]:
# [Answer to Ex. 1.1.3]
first = 4 < 6
second = 4 > 6
third = 4 == 6
fourth = 4 != 6
print(first)
print(second)
print(third)
print(fourth)
print('Input data types are integers, the output types are booleans')

True
False
False
True
Input data types are integers, the output types are booleans


> **Ex. 1.1.4**: Use the functions `abs`, `round` to return the absolute value of -3.14159265 with 3 decimals.

In [5]:
# [Answer to Ex. 1.1.4]
pie = -3.14159265
print('The absolute value of pi is:', round(abs(pie), 3)) 

The absolute value of pi is: 3.142


### Exercise Section 1.2: Logic and loops

> **Ex. 1.2.1**: `if` & `else`     
    Imagine that we have a car that can fit 5 passengers, and we want to know, if the car can fit more passengers.    
        Using 'if' and 'else', make a piece of code that prints out "The car is full" if *passengers* is 5 or more, and "The car is not full yet" if *passengers* are less than 5.

> *Note*: Multiple conditions can be inserted with **elif** statement(s):


In [6]:
# [Answer to Ex. 1.2.1]
print("Enter amount of passengers: ")
passengers = int(input())

if passengers >= 5:
    print("The car is full")
else:
    print("The car is not full yet")


Enter amount of passengers: 


 4


The car is not full yet


> **Ex. 1.2.2**: compute and print each element in the range 1 to 5 cubic (i.e. lifted to power 3) using a `for` loop 

> *Hint*: Python's `range` may be useful

In [7]:
# [Answer to Ex. 1.2.2]
for element in range(1,6):
    power = element**3
    print(power)

1
8
27
64
125


> **Ex. 1.2.3**: Now make a  `while` loops that prints the square (i.e. lifted to power 2) of all the values from 1 to 12.

> *Hint*: Add 1 to your iterator variable at the end of each loop. (You can use the += operator this)

In [8]:
# [Answer to Ex. 1.2.3]
i = 1
while i <= 12:
    print(i**2)
    i += 1

1
4
9
16
25
36
49
64
81
100
121
144


### Exercise Section 1.3: Container and arrays 

> **Ex. 1.3.1**: make two lists, `A` and `B` with respectively integers 2,3,1 and 3,7,4. What is the index of 3 in list Β?

In [9]:
# [Answer to Ex. 1.3.1]
A = [2, 3, 1]
B = [3, 7, 4]

# Index of 3 in list B i 0
print(B[0])

3


> **Ex. 1.3.2**: make a list `C` which consist of first `A`, then `B`. How might we describe this list? Convert `C` into a `numpy array` named `C_a`. What are the dimensions `C` after being converted to an array.

> *Hint 1*: you must import `numpy` before you make the array

> *Hint 2*: numpy arrays have the attribute `shape`.

In [10]:
# [Answer to Ex. 1.3.2]
C = [A, B]
C
import numpy as np
C_a = np.array(C)
np.shape(C_a)

(2, 3)

It is often useful to access lists through its indices. Let `L=[0,2,1,3]`. Slicing of a list works  by returning a subsequence: `B[2:]` returns `[1,3]` and `L[1:3]` returns `[2,1]`.


> **Ex. 1.3.3**:       
- Use `in` operator to check if which values are in `B`
- Slice `B` to print only its second and third element

In [11]:
# [Answer to Ex. 1.3.3]
L = [0, 2, 1, 3]

print(B)
# check if 3 is in B
print(3 in B)
print(5 in B)
print(B[1:3])

[3, 7, 4]
True
False
[7, 4]


We can change the elements in a list. Substitution of an element in the list can be done by slicing.

> **Ex. 1.3.4**:  replace middle element of `B` with 9

In [12]:
# [Answer to Ex. 1.3.4]
B[1] = 9
print(B)

[3, 9, 4]


> **Ex. 1.3.5**: Use functions for containers: Use `max` to find the maximal value of B, and `sorted` to print the elements in B from low to high

In [13]:
# [Answer to Ex. 1.3.5]
max(B)
sorted(B)

[3, 4, 9]

> **Ex. 1.3.6**: try to add `B` to `A`. What is the new length of `A`? Are lists mutable? (e.i. can you change them?)

> *Hint*: one way of doing this is with `append`. Adding elements to a list can be done as `L.append(O)` where `L` is our list and `O` is the object we add.

> *Note*: More methods for lists can be seen [here](https://docs.python.org/3/tutorial/datastructures.html#more-on-lists), including removal of elements with **pop** and **remove**.

In [14]:
# [Answer to Ex. 1.3.6]
A = A + B
A
len(A)
# List are muteable, we can add and delete elements in whatever order we want.

6


> **Ex. 1.3.7 - BONUS**: Convert `A`, `B` into sets named respectively `A_s`, `B_s`. Combine the set `A_s` and `B_s` into one set `C_s`. How many elements are there in `C_s`?

> Note: read about the `set` container in Python [here](https://docs.python.org/3.6/tutorial/datastructures.html#sets).

In [25]:
# [Answer to Ex. 1.3.7]
A_s = set(A)
B_s = set(B)

C_s = A_s | B_s
C_s
print(C_s)
print(len(C_s))

{1, 2, 3, 4, 9}
5


### Exercise Section 1.4: Reusable code; functions and objects

> **Ex. 1.4.1**: make a function named `my_subtract` that takes two arguments and subtracts the second argument from the first. Try altering the function where the second argument is equal to 3 as default; can you execute the function with only a single argument?

In [32]:
# [Answer to Ex. 1.4.1]
def my_substract(x,y=3):
    sub = x-y
    return sub

my_substract(4)
# Yes, that is possible

1

Numpy arrays is a class like lists, sets, dictonaries ect. Numpy arrays are both fast and easy to work with, when you are doing linear algebra. 

Like other classes Numpy arrays have certain functions, that are specific to Numpy arrays. These functions are called by first specifing the Numpy array, and then the a punctuation follow by the function (e.g. `myarray.sort()`) 

> **Ex. 1.4.2**: compute the sum over all elements in the matrix (i.e. 2d-array), `C_a`. Transpose the matrix `C_a`.

> *Hint*: numpy has the function `sum` which may be of use

In [37]:
# [Answer to Ex. 1.4.2]
print(C_a)
C_sum = np.sum(C_a)
print(C_sum)

C_t = C_a.T
print(C_t)

[[1 2 3]
 [3 4 7]]
20
[[1 3]
 [2 4]
 [3 7]]


> **Ex. 1.4.3 - BONUS**: Make a class called employee, which take the arguments first_name, last_name and pay. Use it to make an object `employee_1`, and then print the first name, last name, and the pay of the employee. 


> *Hint:* Within the class you need first to define the "\_\_init\_\_" function, which take the argument *self*

In [38]:
# [Answer to Ex. 1.4.3]
class employee:
    def __init__(self, first_name, last_name, pay):
        self.first_name = first_name
        self.last_name = last_name
        self.pay = pay

In [45]:
employee_1 = employee("John", "Myers", 10000)
print(employee_1.first_name)
print(employee_1.last_name)
print(employee_1.pay)

John
Myers
10000
